### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by vintorez** [swetlana-spb/hlook#1]
1) не понятно зачем в парсере нужна переменная dataList и весь метод constructDataLine. каждый парсер собирает данные в список, а затем constructDataLine перестраивает их в словарь. почему нельзя сразу собирать словарь? как по мне, dataList это лишняя переменная, которая занимает память и увеличивает возможность ошибки (если перепутать местами строки, то в словарь данные запишутся в неправильные поля).
2) в модели Photos поле master_id это внешний ключ (ForeignKey). тут не нужно изобретать велик :) нужно жестко связать через него модели Photos и Information.
3) и последнее, самое жестокое :) вот такое сохранение записей в бд как тут https://github.com/swetlana-spb/hlook/blob/master/database.py#L23-L36 это очень не красиво. во-первых, из-за отсутствия ForeignKey ты делаешь кучу лишней работы, а во-вторых, ты сохраняешь записи в базу по одной штуке, что довольно дорого для больших файлов. я бы предложил использовать вставку данных пачкой (bulk inserts).

**Comment by swetlana-spb** [comment]
По первому пункту я убрала список. 
По второму и третьему. По документации peewee пакетная вставка реализуется с помощью insert_many. Но принимает он либо словарь с однозначно соответствующими полям ключами (ни больше, ни меньше, как говорится), либо список с указанием соответствия полей. Так как я использую в качестве источника данных список, у которого в качестве элементов словари, то пакетно вставить данные в первую таблицу не получится. Пока что пакетно вставила данные только во вторую таблицу, при этом предварительно подготовив данные для insert_many.
Ну а чтобы пакетно вставить все данные разом, то я бы переделала хранилище в postgresql и все хранила в одной табличке, при этом поле с фотками было типа jsonb. Но тут хранилище mysql, так что такой фокус не удастся.

**Comment by vintorez** [comment]
воу-воу, палехче! ) ты же не будешь каждый раз хранить что-то в json когда тебе нужна будет отдельная таблица. если peewee не умеет вставлять так данные, то это, скорее всего, проблема peewee. не эксперт, но мне кажется что какая-нибудь алхимия может делать такую вставку без всякой магии.
сейчас получилось, что atomic() вообще все в одну команду к бд сделает, как я понимаю. для больших файлов это, скорее всего, будет катастрофа. если atomic() действительно так работает, что все данные занесет в бд в одну команду, то я бы предложил использовать его внутри цикла, а в самом цикле считать сколько записей уже накопилось и сливать их в базу, когда наберется например 100 записей. таким образом за раз в бд будет сливаться по 100 записей.

и еще момент: а ты проверяла, работает ли текущий код? мне вот эта строка кажется подозрительной https://github.com/swetlana-spb/hlook/blob/master/database.py#L25 
судя по документации, там при сохранении возвращается объект целиком, а не только айдишник. а ты его вставляешь в другую таблицу как айдишник. и это срабатывает?

**Comment by swetlana-spb** [comment]
> ты же не будешь каждый раз хранить что-то в json когда тебе нужна будет отдельная таблица

Не, ну конечно не буду каждый раз хранить в jsonb. Просто для конкретно данного случая, мне кажется, это весьма приемлемый вариант.

> для больших файлов это, скорее всего, будет катастрофа

Да, пожалуй. Переписала этот кусочек, но не с использованием atomic(), а с помощью batch_commit(). Он как раз позволяет пачками коммитить в БД.

> а ты проверяла, работает ли текущий код? 

Обижаешь! Конечно проверяла. :) Там все нормально отрабатывает.

**Comment by vintorez** [comment]
> Просто для конкретно данного случая, мне кажется, это весьма приемлемый вариант.

не, не стоит жестко завязываться под конкретную бд

> Переписала этот кусочек с помощью batch_commit(). Он как раз позволяет пачками коммитить в БД

👍 

> Там все нормально отрабатывает

да, но ожидаемое ли это поведение? например в списке photos теперь хранятся целые объекты ради одного адишника. действительно ли это необходимый шаг?
но вообщем, ок, это все мелочи. можно считать, что закрыли тему )

теперь насчет архитектуры:
- подключение к бд происходит в методе, который непосредственно работает с самой бд. не стоит так делать. лучше вынести подключение в момент, предшествующий вызовам методов, которые работают с базой. в идеале вообще подключаться к базе при запуске скрипта. таким образом мы создаем одно подключение и можем потом дергать методы работы с базой (а не создавать подключение на каждый вызов метода). плюс, если подключение к базе отвалится, то мы узнаем об этом сразу, а не после того, как парсер, пыхтя, обработал тяжелый файл :)
- предложение на будущее: сделать скрипт независимым от базы данных. то есть дать пользователю возможность самому решать какую бд он хочет использовать. для этого надо будет добавить флаг, который принимает значения mysql или postgres (для начала этих 2 бд вполне хватит). в зависимости от флага, вызывается метод подключения к той или иной бд. а потом уже вызывается метод работы с данными. получится что-то типа того, что сейчас реализовано с парсерами. реально, можно класс для постгреса не реализовывать, а оставить только mysql, но при этом архитектура будет отвязано от конкретной бд и, когда понадобиться, то будет легко реализовать работу с постресом или sqlite

**Comment by swetlana-spb** [comment]
Постаралась учесть замечания на счет архитектуры. 
В частности, добавила, так сказать, "задел" на то, что может быть реализована загрузка не только в mysql.

**Comment by swetlana-spb** [comment]
Ну, вроде все.
